quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  flyway:
    migrate-at-start: true
    baseline-version: 0
    baseline-on-migrate: true
  http:
    auth:
      basic: true
#    ssl-port: 8443
#    ssl:
#      certificate:
#        key-store-file: myapp.keystore
#        key-store-password: mypass
#    cors:
#      origins: *
#      allowed-methods: GET, POST, PUT, DELETE
#      headers:
#        - X-My-Custom-Header
