quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://customerdb:5432/postgres
    password: postgres
    username: postgres
  flyway:
    migrate-at-start: true
    baseline-version: 0
    baseline-on-migrate: true
  http:
    header:
      "X-My-Header":
        value: hello
    auth:
      policy:
        admin-authenticated:
          roles-allowed: admin
      permission:
        authenticated:
          paths: /*
          policy: authenticated
        admin-authenticated:
          paths: /create.html
          policy: admin-authenticated
        permitted:
          paths:
            - "/"
            - "/style.css"
            - "/images"
          policy: permit

  security:
    users:
      file:
        enabled: true
        users: test-users.properties
        roles: test-roles.properties
        realm-name: Quarkus Demo
        plain-text: true

###  for remote dev mode ###
#  package:
#    type: mutable-jar
#  live-reload:
#    password: changeit
#    url: http://localhost:8080

### comment this for remote dev mode###
"%dev":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost:5432/postgres

mp:
  context:
    ThreadContext:
      cleared: Transaction


example:
  greeting: Hello world
  integer: 123
  boolean: true
  origin:
    name: Colombia
    continent: South America
  countries:
    - Colombia
    - Ethiopia
    - Brazil
