'%dev':
  quarkus:
    http:
      port: 8082
quarkus:
  datasource:
    db-kind: h2
    jdbc:
      max-size: 2
      min-size: 1
      url: jdbc:h2:mem:test
    username: username-default
  hibernate-orm:
    database:
      generation: drop-and-create
    dialect: org.hibernate.dialect.H2Dialect
    sql-load-script: META-INF/import.sql
  http:
    cors: true
