version: '3.8'

services:
  coffee-shop-db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dkrnet

  barista:
    image: wiremock/wiremock:2.33.2
    ports:
      - "8081:8080"
    networks:
      - dkrnet

  coffee-shop:
    image: coffee-shop:mutable
    environment:
      QUARKUS_LAUNCH_DEVMODE: "true"
      QUARKUS_LIVE_RELOAD_PASSWORD: "123"
      QUARKUS_LIVE_RELOAD_URL: "http://localhost:8080"
    ports:
      - "8080:8080"
    networks:
      - dkrnet
    depends_on:
      - coffee-shop-db
      - barista

networks:
  dkrnet:
