version: '3.8'

services:
  coffee-shop-db:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dkrnet

  barista:
    image: wiremock/wiremock:2.33.2
    restart: always
    ports:
      - "8081:8080"
    networks:
      - dkrnet

  coffee-shop:
    image: coffee-shop
    restart: always
    ports:
      - "8080:8080"
    networks:
      - dkrnet
    depends_on:
      - coffee-shop-db
      - barista

networks:
  dkrnet:
