version: '3.7'

services:

  db:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_DB: vertx-stock-broker
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - vertx-stock-broker-data-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:4
    ports:
      - "8081:8080"

volumes:
  vertx-stock-broker-data-local:
